language:  python
services:
  - docker

python:
  - "3.6"
install:
  - make deps
script:
  - make lint
  - make docker_build
  - make docker_push

deploy:
  provider: heroku
  app: arcane-hamlet-10587
  api_key: ${HEROKU_API_KEY1}
