language: python
python:
  - "3.6"
install:
  - make deps
script:
  - make test

deploy:
  provider: heroku
  app: shielded-falls-22933
  api_key: ${HEROKU_API_KEY}

after_success:
  - make docker_build
