language:  python
services:
  - docker

python:
  - "3.6"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push

deploy:
  provider: heroku
  app: shielded-falls-22933
  api_key: ${HEROKU_API_KEY}
